import socket
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind(('localhost', 12345))
server.listen(1)
print('Server listening...')
conn, addr = server.accept()
print('Connected by', addr)
data = conn.recv(1024)
print('Received:', data.decode())
conn.sendall(b'Hello from server!')
conn.close()
